CREATE TABLE `games` (
  `gameid` int(11) NOT NULL AUTO_INCREMENT,
  `teamid` int(11) NOT NULL,
  `scheduleflag` varchar(45) DEFAULT NULL,
  `matchid` int(11) NOT NULL COMMENT '대회아이디',
  `exclass` varchar(50) NOT NULL COMMENT '경기레벨(1군.2군등등)',
  `oppoteam` varchar(255) NOT NULL COMMENT '상대팀명',
  `gamedate` datetime NOT NULL COMMENT '경기일시',
  `location` varchar(255) NOT NULL COMMENT '경기장소',
  `weather` varchar(255) NOT NULL COMMENT '경기날씨',
  `fw` int(11) NOT NULL COMMENT '최전방 선수 평가 점수',
  `mf` int(11) NOT NULL COMMENT '미드필드  평가 점수',
  `df` int(11) NOT NULL COMMENT '수비 평가 점수 ',
  `org` int(11) NOT NULL COMMENT '조직력 평가점수',
  `fig` int(11) NOT NULL COMMENT '체력 평가점수',
  `setplay` int(11) NOT NULL COMMENT '세트플레이 점수',
  `fhwrecord` int(11) NOT NULL,
  `fhorecord` int(11) NOT NULL,
  `shwrecord` int(11) NOT NULL,
  `shorecord` int(11) NOT NULL,
  `result` varchar(255) NOT NULL COMMENT '승패결과',
  `formation` varchar(255) NOT NULL COMMENT '포메이션 ',
  `description` varchar(1000) DEFAULT NULL COMMENT '비고 및 설명',
  `fw_description` text COMMENT '공격수들 기록 ',
  `mf_description` text COMMENT '미드필더진 기록 ',
  `df_description` text COMMENT '수비 평가 기록',
  `youtubesource` varchar(500) DEFAULT NULL COMMENT '유투브 소스 ',
  `creationdate` datetime NOT NULL,
  `lastupdatedate` datetime NOT NULL,
  PRIMARY KEY (`gameid`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
